#!/usr/bin/env python

import time
import requests
import json
import urllib3
from prometheus_client.core import GaugeMetricFamily, REGISTRY, CounterMetricFamily
from prometheus_client import start_http_server

class PiholeCollector(object):

    def __init__(self):
        # Disable if you've actually got a good cert set up.
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    def collect(self):

        summary_url = "https://localhost:443/api/stats/summary"
        req = requests.get(summary_url, verify = False,
                           headers = {"accept": "application/json"})

        reply = json.loads(req.text)

        query_types = GaugeMetricFamily("pihole_query_by_type_24h",
                "Count of queries by type over 24h", labels=["query_type"])

        for item in reply["queries"]["types"].items():
            labels = [item[0]]
            value = item[1]
            query_types.add_metric(labels, value)

        yield query_types

        status_types = GaugeMetricFamily("pihole_query_by_status_24h",
                "Count of queries by status over 24h", labels=["query_status"])

        for item in reply["queries"]["status"].items():
            labels = [item[0]]
            value = item[1]
            status_types.add_metric(labels, value)

        yield status_types

        reply_types = GaugeMetricFamily("pihole_query_replies_24h",
                "Count of replies by type over 24h", labels=["reply_type"])

        for item in reply["queries"]["replies"].items():
            labels = [item[0]]
            value = item[1]
            reply_types.add_metric(labels, value)

        yield reply_types

        total_counts = GaugeMetricFamily("pihole_query_count",
                "Query counts by category, whole database", labels=["category"])
        
        total_counts.add_metric(["total"], reply["queries"]["total"])
        total_counts.add_metric(["blocked"], reply["queries"]["blocked"])
        total_counts.add_metric(["unique"], reply["queries"]["unique_domains"])
        total_counts.add_metric(["forwarded"], reply["queries"]["forwarded"])
        total_counts.add_metric(["cached"], reply["queries"]["cached"])

        yield total_counts

        # Yes, I skipped percent_blocked.  We can calculate that in Grafana.
        # Better to not provide data that can be derived from other data.

        clients = GaugeMetricFamily("pihole_client_count",
                "Total/active client counts", labels=["category"])
        
        clients.add_metric(["active"], reply["clients"]["active"])
        clients.add_metric(["total"], reply["clients"]["total"])

        yield clients

        gravity = GaugeMetricFamily("pihole_domains_being_blocked",
                "Number of domains on current blocklist", labels=[])
        
        gravity.add_metric([], reply["gravity"]["domains_being_blocked"])

        yield gravity
        
        
        

if __name__ == '__main__':
    start_http_server(9666)
    REGISTRY.register(PiholeCollector())
    while True:
        time.sleep(1)

